### ISSUE TITLE
There is no way to republish if extend the CAS hierarchy.

### ISSUE THREAD

**Issue by tahakogi** [MicrosoftDocs/SCCMDocs.ja-jp#29]
Once the update has been published in a standalone hierarchy, the content download source is registered as WSUS content on the server.

If you then extend the CAS hierarchy, the download source of the content is fixed with the information in the standalone hierarchy and can not be republished.
We need to edit SUSDB to fix this.

For this reason, it should be stated that it is necessary to re-install SUP and WSUS in the scenario of expanding the hierarchy as a premise.
---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 054797d3-c4d8-2c2e-9940-e8763f6f3881
* Version Independent ID: 9751d801-35de-ebd8-29ea-57e459f845dc
* Content: [サード パーティの更新プログラムを有効にする - Configuration Manager](https://docs.microsoft.com/ja-jp/sccm/sum/deploy-use/third-party-software-updates)
* Content Source: [sccm/sum/deploy-use/third-party-software-updates.md](https://github.com/Microsoft/SCCMDocs.ja-jp/blob/live/sccm/sum/deploy-use/third-party-software-updates.md)
* Product: **configuration-manager**
* Technology: **configmgr-sum**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by CeciAc** [comment]
Hello, @tahakogi

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/SCCMdocs/issues/1640

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
